const Database = require('better-sqlite3');
const { load } = require('sqlite-vec');
const db = new Database(':memory:');
load(db);
db.exec('CREATE VIRTUAL TABLE vec_test USING vec0(embedding float[512])');
db.prepare('INSERT INTO vec_test (embedding) VALUES (?)').run(JSON.stringify([0.1,0.2,0.3]));
const row = db.prepare('SELECT embedding FROM vec_test').get();
console.log('type:', typeof row.embedding);
console.log('constructor:', row.embedding?.constructor?.name);
console.log('Is Buffer?', Buffer.isBuffer(row.embedding));
console.log('Is string?', typeof row.embedding === 'string');
console.log('value:', row.embedding);